homebrew_installed_packages:
  - git
  - go
  - wget
  - zsh-history-substring-search


#mas_installed_apps:
#  - { id: 443987910, name: "1Password" }
#  - { id: 497799835, name: "Xcode" }

dotfiles_repo: https://github.com/emctl/dotfiles.git

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'

homebrew_cask_apps:
  - docker
  - visual-studio-code
  - lastpass