homebrew_installed_packages:
  - git
  - goenv
  - wget
  - zsh-history-substring-search
  - kubectl
  - helm
  - minikube
  - mas
  - pipenv
  - pyenv

dotfiles_repo: https://github.com/emctl/dotfiles-1.git
dotfiles_repo_version: emctl-testing

dotfiles_files:
  - .gitignore
  - .aliases
  - .p10k.zsh
  - .zshrc
  - .inputrc
  - .osx
  - .vimrc

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Contacts
  - Keynote
  - Numbers
  - Pages
  - Settings
  - FaceTime
  - Reminders
  - News
  - Maps

homebrew_cask_apps:
  - visual-studio-code
  - lastpass
  - docker
  - notion
  - steam

